#!/usr/bin/env python

import argparse
import subprocess
import sys
from os.path import join as pjoin
from os.path import abspath
import os
import signal
import glob

def parse_args():
    parser = argparse.ArgumentParser(description='Start or stop dropboxhandlers')
    parser.add_argument('command', choices=['start', 'stop'])
    parser.add_argument(
        '--dropbox',
        help='start or stop only the dropboxhandler for this directory',
        default=None
    )

    return parser.parse_args()


def start_handler(handlerdir):
    print("*** Starting dropboxhandler for %s" % handlerdir)
    try:
        subprocess.check_call(
            [
                'dropboxhandler',
                '--daemon',
                '-c', pjoin(handlerdir, 'dropboxhandler.conf'),
                '--pidfile', pjoin(handlerdir, 'pidfile.pid'),
                '--logfile', pjoin(handlerdir, 'log'),
            ]
        )
        print("*** done")
    except subprocess.CalledProcessError:
        print('*** Could not start handler')


def stop_handler(handlerdir):
    print("*** Stopping dropboxhandler for %s" % handlerdir)
    try:
        with open(pjoin(handlerdir, 'pidfile.pid'), 'r') as f:
            pid = int(f.read())
        os.kill(pid, signal.SIGTERM)
        print("*** done")
    except (OSError, IOError):
        print("*** Could not stop handler for dir %s" % handlerdir)


def main():
    args = parse_args()
    if args.dropbox is None:
        dirs = glob.glob('qeana*')
    else:
        dirs = [args.dropbox]


    if args.command == 'stop':
        for dir in dirs:
            stop_handler(abspath(dir))

    if args.command == 'start':
        for dir in dirs:
            start_handler(abspath(dir))


if __name__ == '__main__':
    main()
